# Validate your repository YAML
# https://docs.codecov.com/docs/codecov-yaml#validate-your-repository-yaml
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

# Ignoring Paths
# https://docs.codecov.com/docs/ignoring-paths
# The pattern folder/* will not match recursively in the folder.
# Please use this folder/**/*, which will exclude all files within the given folder.
ignore:
  - "Dotnet.Samples.AspNetCore.WebApi/Data"
  - "Dotnet.Samples.AspNetCore.WebApi/Enums"
  - "Dotnet.Samples.AspNetCore.WebApi/Migrations"
  - "Dotnet.Samples.AspNetCore.WebApi/Models"
  - "Dotnet.Samples.AspNetCore.WebApi/Properties"
  - "Dotnet.Samples.AspNetCore.WebApi/Utilities"
  - "Dotnet.Samples.AspNetCore.WebApi/Program.cs"
  - "Dotnet.Samples.AspNetCore.WebApi.Tests"

coverage:
  status:
    # Splitting up projects
    # https://docs.codecov.com/docs/commit-status#splitting-up-projects-example
    project:
      controllers:
        paths:
          - "Dotnet.Samples.AspNetCore.WebApi/Controllers/"
      services:
        paths:
          - "Dotnet.Samples.AspNetCore.WebApi/Services/"
    patch:
      default:
        informational: true
