apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cloud-readiness-assessment
  title: Cloud Readiness Assessment
  description: Template to assess cloud readiness of a GitHub repository using Cloud Suitability Analyzer
spec:
  type: service
  owner: team-a
  parameters:
    - title: Repository Information
      properties:
        repoUrl:
          title: GitHub Repository URL
          type: string
          description: The URL of the GitHub repository to assess
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        targetBranch:
          title: Target branch with fix (if any)
          type: string
          description: The name of the target branch in which fix will be checked-in
        name:
          title: Component Name
          type: string
          description: The name of the component to create
  steps:
    - id: clone-repo
      name: Clone Repository
      action: custom:git-clone
      input:
        repoUrl: ${{ parameters.repoUrl }}
        targetPath: C:\Backstageapp\myapp\workspace\repo

    - id: analyze
      name: Analyze Repository
      action: custom:cloud-suitability-analyzer
      input:
        repoUrl: ${{ parameters.repoUrl }}
        targetBranch: ${{ parameters.targetBranch }}
        targetPath: C:\Backstageapp\myapp\workspace\repo
      output:
        taskId: ${{ steps.clone-repo.output.taskId }} # Ensure taskId is set here if available
  output:
    repoUrl: ${{ parameters.repoUrl }}
    links:
      - title: Cloud Readiness Report
        url: /cloud-readiness-report

