apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-vm-template
  title: Azure VM Template
  description: Template to create an Azure VM for 2 days
spec:
  owner: team-a
  type: service

  parameters:
    - title: VM Configuration
      properties:
        vmName:
          title: VM Name
          type: string
        resourceGroupName:
          title: Resource Group Name
          type: string
        location:
          title: Location
          type: string
          enum:
            - eastus
            - westus
            - westeurope
            - southeastasia
        adminUsername:
          title: Admin Username
          type: string
          ui:field: Secret
        adminPassword:
          title: Admin Password
          type: string
          ui:field: Secret

  steps:
    - id: fetch-arm-template
      name: Fetch ARM Template
      action: fetch:template
      input:
        url: https://github.com/mishraabhay2010/dotnetcore-webapi-template/blob/main/azure-arm-templates/vmwindow.json
        values:
          vmName: ${{ parameters.vmName }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          location: ${{ parameters.location }}
          adminUsername: ${{ secrets.adminUsername }}
          adminPassword: ${{ secrets.adminPassword }}
    - id: list-files
      name: List Files
      action: shell:script12
      input:
        script: ls -la mypath  

