apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-containerization-template 
  title: App Containerization Template 
  description: Template for application cloud assessment and containerization
  tags:
    - containerization
    - automation
    - cloud assessment
spec:
  type: service
  owner: team-a
  system: production
  actions:
    shell:script:
      description: "Run a shell script"
      inputs:
        script:
          description: "The shell script to run"
          required: true
      runs:
        using: "shell"
        main: "${{ inputs.script }}"

  parameters:
    - title: Project Name
      description: The name of the project
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Assess source code for cloud migration and set up containerization workflow
    - title: Choose a Repository location
      required:
        - location
      properties:
        location:
          title: Source Repository Location
          type: string
          description: Repository location
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Containerization Configuration 
      description: Configuration for containerization setup
      required:
        - gocdPipelineName
        - gocdServerUrl
      properties:
        gocdPipelineName:
          title: Job Name
          type: string
          description: Name of the containerization job
        gocdServerUrl:
          title: Cloud Assessment Server URL 
          type: string
          description: URL of the Cloud Assessment server

  steps:
    - id: fetch-repository
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.location | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          pipelineName: ${{ parameters.gocdPipelineName }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.location }}
    - id: configure-gocd
      name: Configure GOCD
      action: shell:script
      input:
        script: |
          echo "Configuring GOCD pipeline..."
          echo {^
           "group": "testpipeline",^
            "pipeline": {^
              "name": "${{ parameters.gocdPipelineName }}",^
              "display_order_weight": -1,^
              "label_template": "${COUNT}",^
              "lock_behavior": "none",^
              "environment_variables": [],^
              "parameters": [],^
              "materials": [^
                {^
                  "type": "git",^
                  "attributes": {^
                    "url": "${{ steps.publish.output.remoteUrl }}",^
                    "branch": "master",^
                    "shallow_clone": false,^
                    "auto_update": true^
                  }^
                }^
              ],^
              "stages": [^
                {^
                  "name": "build",^
                  "fetch_materials": true,^
                  "never_cleanup_artifacts": false,^
                  "clean_working_directory": false,^
                  "approval": {^
                    "type": "success",^
                    "authorization": {^
                      "users": [],^
                      "roles": []^
                    },^
                    "allow_only_on_success": false^
                  },^
                  "environment_variables": [],^
                  "jobs": [^
                    {^
                      "name": "build",^
                      "environment_variables": [],^
                      "tabs": [],^
                      "resources": [],^
                      "artifacts": [],^
                      "timeout": null,^
                      "tasks": [^
                        {^
                          "type": "exec",^
                          "attributes": {^
                            "run_if": ["passed"],^
                            "command": "dotnet",^
                            "args": ["build"]^
                          }^
                        }^
                      ]^
                    }^
                  ]^
                },^
                {^
                  "name": "test",^
                  "fetch_materials": true,^
                  "never_cleanup_artifacts": false,^
                  "clean_working_directory": false,^
                  "approval": {^
                    "type": "success",^
                    "authorization": {^
                      "users": [],^
                      "roles": []^
                    },^
                    "allow_only_on_success": false^
                  },^
                  "environment_variables": [],^
                  "jobs": [^
                    {^
                      "name": "test",^
                      "environment_variables": [],^
                      "tabs": [],^
                      "resources": [],^
                      "artifacts": [],^
                      "timeout": null,^
                      "tasks": [^
                        {^
                          "type": "exec",^
                          "attributes": {^
                            "run_if": ["passed"],^
                            "command": "dotnet",^
                            "args": ["test"]^
                          }^
                        }^
                      ]^
                    }^
                  ]^
                }^
              ]^
            }^
    
          }^ > gocd-config.json
          echo "Configuring GOCD pipeline ending..."
          curl -u "user:user" -H "Accept: application/vnd.go.cd.v11+json" -H "Content-Type: application/json" -H "X-pause-pipeline: true" --data-binary @gocd-config.json ${{ parameters.gocdServerUrl }}/go/api/admin/pipelines
    - id: set-permissions
      name: Set Repository Permissions
      action: github:set-permissions
      input:
        owner: ${{ parameters.owner }}
        name: ${{ parameters.location }}
    - id: create-component
      name: Create Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
