apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: jira-to-code-AIForce
  title: Jira ticket to code template powered by AIForce
  description: Template to generate programming code using Jira Description powered by AIForce
spec:
  owner: team-a
  type: service

  parameters:
    - title: Jira Ticket Information
      properties:
        jiraId:
          title: Jira ticket ID
          type: string
          description: Jira ticket ID
        programminglang:
          title: Programming Language
          type: string
          description: Programming Language
      required:
        - jiraId
        - programminglang

  steps:
    - id: fetch-jira-issue
      name: Fetch Jira issue
      action: custom:jiraconnector
      input:
        jiraId: ${{ parameters.jiraId }}
    - id: aiforce-data-prep
      name: AIForce data Preperation
      action: aiforce:dataprep
      input:
        filepath: ${{ steps['fetch-jira-issue'].output.filePath }}
    - id: aiforce-usecase-execution
      name: AIForce Usecase execution
      action: aiforce:usecaseexecution
      input:
        data: ${{ steps['aiforce-data-prep'].output.latestData }}
        programminglang: ${{ parameters.programminglang }}

  output:
    links:
      - title: Report
        url: /ai-force-report?job_name=${{ steps['aiforce-usecase-execution'].output.job_name }}&execution_id=${{ steps['aiforce-usecase-execution'].output.execution_id }}
        
    
