apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: container-migration
  title: Container Migration Template
  description: Template for kubernetes migration 
  tags:
    - kubernetes
    - container-migration
    - migration
spec:
  type: service
  owner: team-a
  parameters:
    - title: Source Container Information
      required:
        - sourceNamespace
        - sourcePod
        - sourceContainer
      properties:
        sourceNamespace:
          title: Source Namespace
          type: string
          description: The namespace of the source container
        sourcePod:
          title: Source Pod
          type: string
          description: The pod name of the source container
        sourceContainer:
          title: Source Container
          type: string
          description: The name of the source container
    - title: Target Container Information
      required:
        - targetNamespace
        - targetPod
        - targetContainer
      properties:
        targetNamespace:
          title: Target Namespace
          type: string
          description: The namespace of the target container
        targetPod:
          title: Target Pod
          type: string
          description: The pod name of the target container
        targetContainer:
          title: Target Container
          type: string
          description: The name of the target container
    - title: Migration configuration 
      required:
        - veleroNamespace
        - backupName
        - restoreName
      properties:
        veleroNamespace:
          title: Velero Namespace
          type: string
          description: The namespace where Velero is installed
        backupName:
          title: Backup Name
          type: string
          description: The name of the Velero backup
        restoreName:
          title: Restore Name
          type: string
          description: The name of the Velero restore

  steps:
    - id: create-backup
      name: Create Velero Backup
      action: shell:script
      input:
        script: |
          echo "Creating Velero backup..."
          kubectl -n ${{ parameters.veleroNamespace }} exec deploy/velero -- velero backup create ${{ parameters.backupName }} --include-namespaces ${{ parameters.sourceNamespace }}
          echo "Velero backup created."

    - id: create-restore
      name: Create Velero Restore
      action: shell:script
      input:
        script: |
          echo "Creating Velero restore..."
          kubectl -n ${{ parameters.veleroNamespace }} exec deploy/velero -- velero restore create ${{ parameters.restoreName }} --from-backup ${{ parameters.backupName }} --namespace-mappings ${{ parameters.sourceNamespace }}:${{ parameters.targetNamespace }}
          echo "Velero restore created."

  output:
    links:
      - title: Kubernetes Dashboard
        url: https://kubernetes-dashboard-url
