---
exclude_paths:
  - ".github"
  - ".vscode"
  - ".gitignore"
  - "LICENSE"
  - "README.md"
  - "**.sln"
  - "**.csproj"
  - "**.json"
  - "**.yml"
  - "**/*Program.cs"
  - "**/Data/**"
  - "**/Enums/**"
  - "**/Migrations/**"
  - "**/Models/**"
  - "**/Properties/**"
  - "**/Utilities/**"
  - "**.Tests/**"
